import os 
x=__import__(os.environ['DJANGO_SETTINGS_MODULE'],'','',[''])
MEDIA_ROOT = x.MEDIA_ROOT

SITE_ID = x.SITE_ID

MEDIA_URL = x.MEDIA_URL

print os.environ['DJANGO_SETTINGS_MODULE']
ADMIN_MEDIA_PREFIX = '/adminmedia/'

UPLOAD_DIR=x.UPLOAD_DIR

COOKIE_DOMAIN=x.COOKIE_DOMAIN

IMG_MODE=x.IMG_MODE
IMG_QUALITY=x.IMG_QUALITY
IMG_WIDTH=x.IMG_WIDTH
IMG_HEIGHT=x.IMG_HEIGHT

#CATEGORY_IMG_WIDTH=IMG_WIDTH
#CATEGORY_IMG_HEIGHT=IMG_HEIGHT
#
#CHOICE_IMG_WIDTH=IMG_WIDTH
#CHOICE_IMG_HEIGHT=IMG_HEIGHT

DATABASE_ENGINE = x.DATABASE_ENGINE 
DATABASE_NAME = x.DATABASE_NAME
DATABASE_USER = x.DATABASE_USER
DATABASE_PASSWORD = x.DATABASE_PASSWORD 
DATABASE_HOST = x.DATABASE_HOST
DATABASE_PORT = x.DATABASE_PORT

#NUM_ARTICLES_FRONTPAGE=x.NUM_ARTICLES_FRONTPAGE

# URLS
ABS_URL= x.ABS_URL

#REQUIRE_EVENT_APPROVAL = x.REQUIRE_EVENT_APPROVAL

##
#WEATHER_PARTNER=x.WEATHER_PARTNER
#WEATHER_ZIP=x.WEATHER_ZIP

#RECAPTCHA_PUB_KEY=x.RECAPTCHA_PUB_KEY

#try:
#    TZONE_ADJUST=x.TZONE_ADJUST
#except AttributeError:
#    TZONE_ADJUST=0